### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by KristjanESPERANTO** [btoconnor/MMM-WMATA#10]
It would be nice if you could add a screenshot to your repository. This will allow users to see what the module looks like, and it will also be used in [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/).

**Comment by btoconnor** [comment]
Just hadn't merged the commit. Done now

**Comment by KristjanESPERANTO** [comment]
Nice. Now one can see the screenshot in the README, but for showing up in the new module list it has to be in the repository and not in your personal GitHub space.

**Comment by btoconnor** [comment]
Ah - thanks for the tip. I'll get that sorted out.

**Comment by btoconnor** [comment]
Okay that should be resolved now with #11 .  Let me know if that doesn't meet the requirements.

**Comment by KristjanESPERANTO** [comment]
Perfect. Thanks!
